Fix IllegalAccessError
The same class from different jar files (e.g. ToStringBuilder) causes the following error in some Dalvik devices:
> java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation